feat: style profile page and add functionality to buttons
utk-cs340-fall24/SolSync pull request #61
Opened 2024-10-14 05:33 UTC by amy-huang16

# Description
Profile page is now just missing displayName connection to backend and edit functionality

## Relevant Issues
#46

2024-10-14 15:41 UTC, Trishu-Patel requested changes

2024-10-14 15:41 UTC, Trishu-Patel commented on src/components/Profile/AuthorizedProfile.tsx
> +  const [modalVisible, setModalVisible] = useState(false);
```suggestion
export default function AuthorizedProfile() {
  const [isModalVisible, setIsModalVisible] = useState(false);
```
Boolean variable names should start with is

2024-10-15 01:59 UTC, RudraPatel2003 approved these changes

2024-10-15 02:07 UTC, Trishu-Patel approved these changes

2024-10-15 02:07 UTC, merged